### ISSUE TITLE
Einloggen

### ISSUE THREAD

**Issue by AHeinisch** [FHBielefeld-IFM-WS1718-SWEng1/WebAPI#1]
Ermöglichen des Einloggens mit der API ermöglichen

**Comment by AHeinisch** [comment]
```json
{
 "username":"Benutzername",
 "password":"Password"
}
```

**Comment by fwiese1** [comment]
Also machen wir das Einloggen jetzt doch über die API?

**Comment by AHeinisch** [comment]
Wir werden nur ermöglichen anhand des Logins einen API Key zu erhalten nicht aber auf Rechtschreibfehler/Verschlüsselung etc wert legen. Prinzip what you see is what you get.

Da bei der Plannung immer noch nicht gesagt wurde ob über Username oder E-Mail der Login ermöglicht werden soll. oder vielleicht beides werden wir ein Nutzername und ein verschlüsseltes PW erwarten und ein Json zurück schicken wo das PW nicht nochmal gesendet wird sondern nur die Profildaten und der API Key den der Nutzer ab diesen Zeitpunkt nutzen soll.

**Comment by AHeinisch** [comment]
Einloggen ist möglich erstellt einen API-Key der URL-Safe ist.
