### ISSUE TITLE
Feature Request: Detailliertere Antwort bei task POST requests  

### ISSUE THREAD

**Issue by draeder94** [FHBielefeld-IFM-WS1718-SWEng1/WebAPI#101]
Ich arbeite derzeit an der Aufgabenliste, und mir ist aufgefallen, dass das POST request eine nahezu vollständige Antwort im Stile des GET requests liefert. 

Die tasks im GET request der 'party' Route sieht so aus:
```
{
    "id": 28,
    "text": "Würstchen",
    "status": 0,
    "user_id": 19,
    "party_id": 241126,
    "User": {
        "id": 19,
        "email": "Uli@IchMussKeineSteuernzahlen.knast",
        "name": "Der Uli",
        "birthdate": "1999-12-11",
        "gender": 0,
        "profilepicture": "bild",
        "loginAt": null,
        "deletedAt": null
    }
 }
```

Die Rückgabe des POST dagegen so:
```
{
    "id": 28,
    "user_id": 19,
    "party_id": 241126,
    "text": "Würstchen",
    "status": 0,
    "updatedAt": "2018-01-19T15:52:14.511Z",
    "createdAt": "2018-01-19T15:52:14.511Z"
}
```

Ist es möglich den User block auch in die Antwort des POST mit einzubauen? Das würde es für mich im Frontend deutlich einfacher machen die Aufgabenliste direkt nach dem zufügen um den neuen Eintrag zu erweitern, statt die gesamte Party erneut abzurufen.

**Comment by AHeinisch** [comment]
wird gemacht

**Comment by AHeinisch** [comment]
wurde in der aktuellen version auf den Liveserver eingerichtet

**Comment by draeder94** [comment]
Prinzipiell genau das, was ich brauchte, mit der ausnahme, dass die tasks im GET der Party das Element "User" haben, und die POSt Rückgabe "user".
Wegen der Groß- und Kleinschreibung sind die unterschiedlich und funktionieren nicht :/

**Comment by AHeinisch** [comment]
ist mit den kurzen Test zwar drinne bitte noch einmal ausprobieren

**Comment by draeder94** [comment]
Jetzt gehts, danke :D
