### ISSUE TITLE
creator=true funktioniert auf der party route nicht.

### ISSUE THREAD

**Issue by draeder94** [FHBielefeld-IFM-WS1718-SWEng1/WebAPI#104]
GET request mit:
```
http://api.dleunig.de/party?api=iFKQXkmutu5J2wAIi_7Vp0kwlgS4UuG9EOoSquyeLTg&creator=true
```

Der API Key ist für den user mit ID 31, trotzdem liefert das ganze Parties zurück, die von den Usern 32 und 16 erstellt wurden.

**Comment by draeder94** [comment]
Nachtrag:

Ist es möglich bei GET requests auf der party route (für den allgemeinen Abruf) den Status des abrufenden Nutzers mitzusenden? Würde das Handling in der Home Ansicht für uns deutlich vereinfachen.

**Comment by draeder94** [comment]
Weiterer Nachtrag:

Zuvor wurde der Name des Gastgebers mitgeschickt, jetzt nurnoch die ID. Ich handle derzeit sowohl den ersten nachtrag als auch diesen üver das gleiche, zweite Request, d.H. entweder müssen beide Werte gewährleistet sein oder keiner. Mir prinzipiell Wurst, geht auch so, ist aber ein extra request und dauert daher länger.

**Comment by AHeinisch** [comment]
Zum ersten wenn ein Query Eintrag nicht vorhanden ist also creator/guest dann wird dieser als Default auf true gesetzt.
Zum zweiten Ich würde jetzt die User Daten mitliefern
Zum dritten reicht es einfach nur ein "user":{"id": 12, "name":"Beispiel", "emai":"gültige@email.de"}

**Comment by draeder94** [comment]
Zum ersten: ich muss also zwangsläufig "creatortrue&guest=false" machen?
Zum zweiten: Wäre super
Zum dritten: Ich brauche eigentlich nur den Namen, aber die ID könnte für die anderen evtl relevant sein. Email wird eigentlich nie genutzt, da die ja auch für alle außer die eigene Person unsichtbar ist.

**Comment by AHeinisch** [comment]
oder einfach nur guest=false und creator ist bei default true somit kann der Creator weggelassen werden
