### ISSUE TITLE
Bei PUT auf der party route fehlt das Bild

### ISSUE THREAD

**Issue by draeder94** [FHBielefeld-IFM-WS1718-SWEng1/WebAPI#109]
Wird nicht gespeichert, bleibt null.

**Comment by AHeinisch** [comment]
typo ist behoben
wäre gut wenn einmal getestet wird

**Comment by draeder94** [comment]
Scheint noch nicht zu funktionieren

**Comment by AHeinisch** [comment]
ziemlich sicher das es nun richtig ist -.- schuldige der Umstände

**Comment by draeder94** [comment]
Yup, jetzt läufts, danke ^^
