### ISSUE TITLE
Feature Request: Detailiertere Antwort bei POST guest 

### ISSUE THREAD

**Issue by draeder94** [FHBielefeld-IFM-WS1718-SWEng1/WebAPI#116]
Wäre es möglich, ähnlich wie bei der pary/task route, mit dem POST request auf der party/guest route das neue guest objekt zurückzugeben?

Dann könnte man das direkt in die Arrays einfügen, anstatt die Party neu abzufragen.

**Comment by AHeinisch** [comment]
wird gemacht

**Comment by AHeinisch** [comment]
{
    "id": null,
    "party_id": 7,
    "user_id": 1,
    "updatedAt": "2018-01-23T12:42:24.321Z",
    "createdAt": "2018-01-23T12:42:24.321Z",
    "user": {
        "id": 1,
        "name": "test0"
    }
}

**Comment by AHeinisch** [comment]
so ?

**Comment by draeder94** [comment]
Prinipiell ja, da fehlt noch "status" (was ja nach POST erstmal 0 ist) und denk daran das die Unterkomponente "User " mit großem U beginnt.

**Comment by AHeinisch** [comment]
{
    "id": null,
    "party_id": 6,
    "user_id": 1,
    "status": 0,
    "updatedAt": "2018-01-23T15:59:58.134Z",
    "createdAt": "2018-01-23T15:59:58.134Z",
    "User": {
        "id": 1,
        "name": "test0"
    }
}

Diese Version wird gleich gemerged
