### ISSUE TITLE
Party #241126 ist erneut nicht erreichbar

### ISSUE THREAD

**Issue by draeder94** [FHBielefeld-IFM-WS1718-SWEng1/WebAPI#124]
Könnte das wieder das gleiche Problem mit den Kommentaren sein?
Ich bekomme für ```http://api.dleunig.de/party/241126?api=faul```
wieder nur
```
{
    "error": "Cannot read property 'dataValues' of null"
}
```
zurück

**Comment by draeder94** [comment]
Ein Test mit einer neuen Party zeigt, der User welcher für eine Aufgabe auf null gesetzt wurde (um freiwilliges Melden zu erlauben) scheint diesen Fehler hervorzurufen.

**Comment by AHeinisch** [comment]
im falle das kein User existiert lieber User : null oder User : {}

**Comment by draeder94** [comment]
lieber null.

**Comment by AHeinisch** [comment]
ist behoben
