### ISSUE TITLE
hizufügen einer Route wo nur die email/id und der nutzername zurück gegeben wird

### ISSUE THREAD

**Issue by AHeinisch** [FHBielefeld-IFM-WS1718-SWEng1/WebAPI#38]
es soll nicht mehr möglich sein einfach nur GET /user zu machen da die Funktionen sich aufteilen wie z.b. POST /login ist zuständig für das einloggen eines Users und das anlegen eines API keys.
Die Kontaktliste wäre zuständig für alle Kontakte.
Die GET /party/{id} wäre zuständig für alle Teilnehmer einer Party somit wird diese Route nicht mehr gebraucht.

Ist dies wirklich so absprechen mit PH und Frontends

**Comment by AHeinisch** [comment]
Alles Zurück Route muss nur überarbeitet werden.
Zurück geben von allen Usern name , email/id

**Comment by nloetkemann** [comment]
ist fertig, wird im nächstem PR drin sein

**Comment by nloetkemann** [comment]
erledigt im pr60
