### ISSUE TITLE
GET auf /party liefert doppelte Rückgaben

### ISSUE THREAD

**Issue by draeder94** [FHBielefeld-IFM-WS1718-SWEng1/WebAPI#57]
Sowohl in Postman als im WebFrontend.
Die URL war 
>  http://api.dleunig.de/party?api=vG2twd-w04vYbsLCcco8b1pifQZARtz9RrRYdC-ziwk

und das resultierende Ergebnis:
```{
    "count": 2,
    "parties": [
        {
            "id": 241125,
            "name": "Papst-Party",
            "description": null,
            "startDate": "2011-10-05T14:48:00.000Z",
            "endDate": null,
            "location": "Petersdom",
            "createdAt": "2017-12-21T18:01:56.000Z",
            "updatedAt": "2017-12-21T18:01:56.000Z",
            "deletedAt": null,
            "user_id": 32,
            "ersteller": true
        },
        {
            "id": 241125,
            "name": "Papst-Party",
            "description": null,
            "startDate": "2011-10-05T14:48:00.000Z",
            "endDate": null,
            "location": "Petersdom",
            "createdAt": "2017-12-21T18:01:56.000Z",
            "updatedAt": "2017-12-21T18:01:56.000Z",
            "deletedAt": null,
            "user_id": 32
        }
    ]
}
```

Die gleiche Party zwei mal.
Der Fehler ließ sich mehrfach reproduzieren.

**Comment by AHeinisch** [comment]
wie dringend ist das beheben dieses Fehlers ? =)

**Comment by draeder94** [comment]
Mindestens bis ende Januar? :D

**Comment by AHeinisch** [comment]
Fehler suche hat ergeben das der User 32 also Papst sowohl der Ersteller ist wie auch einer der Gäste somit ist dies eher eines euer Probleme =). Ich kann zwar restriktiv sagen bei jeder Party darf nicht der Ersteller eingeladen werden dies söllte besprochen werden.
Interessieren würde mich auch wer diese Party angelegt hat und wer die Gästelisten Einträge gemacht hat.

Kurzfassung:
in der DB steht der Papst als Ersteller sowie in der Gästeliste zu dieser Party.

**Comment by draeder94** [comment]
Zugefügt hatte ich die, kann mich aber nicht erinnern Personen eingeladen zu haben. Hmm.

**Comment by AHeinisch** [comment]
Wird geschlossen.
Wurde auf dem Livesystem getestet. nicht aufgetreten
Wurde auf dem Devsystem getestet. nicht aufgetreten

Es ist dennoch möglich den Ersteller als Gast in eine Party einzutragen.
