### ISSUE TITLE
GET user/:id existiert nicht mehr

### ISSUE THREAD

**Issue by draeder94** [FHBielefeld-IFM-WS1718-SWEng1/WebAPI#63]
Die Tatsache, dass ein allgemeines GET für alle User existiert ist zwar gut, aber ich glaub ihr habt dabei was wichtiges gelöscht :'D

https://github.com/FHBielefeld-IFM-WS1718-SWEng1/WebAPI/commit/dca9cf6749a35f623fb88d641beae9be7d2ed244#diff-adb7c84bc8a9e9b0d5bde72050f892f5L30

**Comment by draeder94** [comment]
Nachtrag:

Kann es sein, dass GET user/ in der Länge begrenzt ist? In Postman kommen längst nicht alle Nutzer raus.

**Comment by AHeinisch** [comment]
vielen dank das du sogar heraus gefunden wo das her kommt wird als Hotfix eingespielt genauso wie das mit der get /user route
