### ISSUE TITLE
Kontakt Hinzufügen

### ISSUE THREAD

**Issue by draeder94** [FHBielefeld-IFM-WS1718-SWEng1/WebAPI#65]
Evtl. bin ich auch nur doof, aber ist es d.Z. nicht möglich Kontakte zuzufügen?
Eine POST methode auf user/contact gibt es nicht und PUT retuniert:
`"error": "Kein eintrag mit dieser ID!"`

Versuchtes request war:
`PUT http://api.dleunig.de/user/contact?api=o97Ju0Qgy989zPmMqyQOZtag6GKFxj8RwHMM_w4friw`
mit
`{
	"userid": 36
}`

Mach ich was falsch, oder ist das WIP? :D

**Comment by AHeinisch** [comment]
WIP : ) (Vergessen)
wir gemacht und den error bekommst du weil nodejs gemein ist =)
Die variante wie man eine Contactanfrage sendet wäre so richtig bisauf nicht put sonder post.
wird Montag nach der Arbeit getestet und veröffentlicht

**Comment by AHeinisch** [comment]
ETA 1h bis release =)

**Comment by draeder94** [comment]
Dieser Fehler scheint noch nicht vollständig behoben zu sein.
Bei einem POST Request mit body wie oben kommt nun die Meldung:
```
{
    "error": "Field 'User_ID2' doesn't have a default value"
}
```

**Comment by AHeinisch** [comment]
Ok neuer Versuch habe es im aktuellen dev überarbeitet und werde ihn gleich updaten eta 20 min

**Comment by AHeinisch** [comment]
Update ist im Livesystem und muss jetzt Funktionieren

**Comment by nloetkemann** [comment]
funktioniert
