### ISSUE TITLE
GET /party mit creator=true scheint nicht zu funktionieren

### ISSUE THREAD

**Issue by draeder94** [FHBielefeld-IFM-WS1718-SWEng1/WebAPI#66]
Normales GET funktioniert, GET mit guets=true geht auch, mit creator bekomme ich null ergebnisse.

Konkrete Anfrage war
`http://api.dleunig.de/party?api=o97Ju0Qgy989zPmMqyQOZtag6GKFxj8RwHMM_w4friw&creator=true`

Rückgabe:
```
{
    "count": 0,
    "parties": []
}
```

**Comment by AHeinisch** [comment]
Hier sind Falsche Kontrollen von Werten vorhanden wird behoben
