### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by AHeinisch** [FHBielefeld-IFM-WS1718-SWEng1/WebAPI#7]
Schreiben der Route Logout welche das ungültig machen des APIKeys erledigt!

**Comment by AHeinisch** [comment]
wurde diese Route getestet? wurden Tests geschrieben wie ist der status?

**Comment by nloetkemann** [comment]
bisher nur mit postman getestet. Tests mit mocha werden geschrieben

**Comment by nloetkemann** [comment]
logout funktioniert, kann in den master, tests werden noch geschrieben
