### ISSUE TITLE
Error Image Route bei Image senden

### ISSUE THREAD

**Issue by AKirsch1** [FHBielefeld-IFM-WS1718-SWEng1/WebAPI#86]
Body:
{
  "data": "VElNZGllc2VyVElNc3RyaW5nVElNaXN0VElNZWluZmFjaFRJTW51clRJTXp1bVRJTXRlc3RlblRJTQ=="
}

Antwort:
{
    "error": "ENOENT: no such file or directory, open './demo/TsFPIdV2GBAOWqBXpH8ybwHBrsL8Hcnvz3u2VBJwok4.jpg'"
}

**Comment by AHeinisch** [comment]
Dieser Fehler ist lustig.... Lokal nicht reproduzierbar vielleicht behebt die neue Version den Fehler aber bereits
